name: APK Yapici
on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 # v4'e güncellendi

      - name: Python Kurulumu
        uses: actions/setup-python@v5 # v5'e güncellendi
        with:
          python-version: '3.10'

      - name: Gerekli Bagimliliklari Kur
        run: |
          sudo apt update
          sudo apt install -y build-essential git python3-dev ffmpeg libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev libportmidi-dev libswscale-dev libavformat-dev libavcodec-dev zlib1g-dev libsqlite3-dev sqlite3 bzip2 libbz2-dev libreadline-dev libffi-dev libssl-dev
          pip install --upgrade pip
          pip install buildozer cython==0.29.33 setuptools

      - name: Buildozer ile APK Hazirla
        run: |
          buildozer android debug
        # Hata alırsak daha detaylı görebilmek için logları açık tutuyoruz

      - name: APK Dosyasini Yukle
        uses: actions/upload-artifact@v4 # v4'e güncellendi
        with:
          name: VoidRunner-APK
          path: bin/*.apk
