name: APK Yapıcı
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Buildozer ile APK Oluştur
        uses: ArtemSerebriakov/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
          repository_read_token: ${{ secrets.GITHUB_TOKEN }}

      - name: APK'yı Kaydet
        uses: actions/upload-artifact@v2
        with:
          name: UzaySavasi-APK
          path: bin/*.apk
